### ISSUE TITLE
the version involved in the requirements.txt of SpiNNaker

### ISSUE THREAD

**Issue by zby0624** [SpiNNakerManchester/SpiNNCer#1]
I have found the open source code of SpiNNaker on the corresponding github website https://github.com/SpiNNakerManchester/SpiNNCer. Is it convenient to tell me the version involved in the following requirements.txt?such as the version of pyNN,python.

Looking forward to receiving your reply.
Good luck in your work and progress in your research!

**Comment by Christian-B** [comment]
Are you looking for the General SpiNNaker pynn code?
If so that can be found at:
https://github.com/SpiNNakerManchester/sPyNNaker

Or are you interested in something particular to this repository that you did not find in the general sPyNNaker repository?

If so please let us know at the Author of this work has left the project after finishing his PhD and this has now fallen behind.

**Comment by zby0624** [comment]
> 

Thank you for your reply.
I have already found the SpiNNaker pynn code.However, we are not aware of the proper python version to run the code with errors. For example, in the URL https://github.com/SpiNNakerManchester/SpiNNCer/requirements.txt, the version of pyNN, python, etc. If it is convenient, can you give the email contact of the author of the work? The email account (petrut.bogdan@manchester.ac.uk) is shown as cancelled, so it is possible that the author has graduated from the university and left.

Looking forward to receiving your reply.
Good luck in your work and progress in your research!

**Comment by andrewgait** [comment]
Hi - Petrut has moved on from this work, but it is still possible to run it against the main sPyNNaker toolchain if you would like to, though the instructions for doing this depend somewhat on how and where you plan to run the code from.  Assuming this is what you want to do please let us know how and where you want to try running this code from and we can give you advice as to the best way to do this.

**Comment by zby0624** [comment]
Thank you for your prompt response. I would like to know the version of python or pyNN required to run the code,which is the version involved in https://github.com/SpiNNakerManchester/SpiNNCer/requirements.txt.

I am sorry for the trouble and look forward to your reply.Good luck in your work and progress in your research!

**Comment by andrewgait** [comment]
I can tell you that I have successfully run this code (from our local servers in Manchester) using python 3.8 and pyNN 0.9.6, but I'm not sure how much that will help you without knowing how you're trying to run it as there are plenty of other things you need to do as well in order to make it work.

**Comment by zby0624** [comment]
> I can tell you that I have successfully run this code (from our local servers in Manchester) using python 3.8 and pyNN 0.9.6, but I'm not sure how much that will help you without knowing how you're trying to run it as there are plenty of other things you need to do as well in order to make it work.

Thank you for your reply. I apologize for just posting the link to the wrong requirements.txt, I would also like to know the NEST version to ensure the code works correctly.

Looking forward to receiving your reply.
Good luck in your work and progress in your research!

**Comment by andrewgait** [comment]
I haven't run NEST myself in this instance, but the 2019 paper (Casali et al) linked to in the README tells me they used pyNEST version 2.14.  You may also find it helpful to read Petrut's more recent paper on the work he did using this repository, which is at https://www.frontiersin.org/articles/10.3389/fncel.2021.622870/full (and I have added this link to the README as well).

**Comment by zby0624** [comment]
> I haven't run NEST myself in this instance, but the 2019 paper (Casali et al) linked to in the README tells me they used pyNEST version 2.14. You may also find it helpful to read Petrut's more recent paper on the work he did using this repository, which is at https://www.frontiersin.org/articles/10.3389/fncel.2021.622870/full (and I have added this link to the README as well).

Okay, thank you for your reply!

**Comment by Christian-B** [comment]
assuming resolved.
